<?php
require __DIR__.'/includes/bootstrap.php';require_permission('campaigns.view');$pdo=db();
$campaigns=$pdo->query('SELECT c.*,e.full_name manager_name,(SELECT COUNT(*) FROM campaign_registrations cr WHERE cr.campaign_id=c.id AND cr.counted=1) counted FROM campaigns c LEFT JOIN employees e ON e.id=c.manager_employee_id ORDER BY c.start_date DESC')->fetchAll();foreach($campaigns as &$c)$c['progress']=campaign_progress($c,(int)$c['counted'],0);unset($c);
$employees=$pdo->query("SELECT id,full_name FROM employees WHERE employment_status='active' ORDER BY full_name")->fetchAll();$title='Campaigns & Targets';$active='campaigns';include __DIR__.'/includes/header.php';
?>
<section class="section-toolbar reveal"><div><p class="eyebrow">Target control</p><h2>Campaigns & growth targets</h2><p class="muted">Create, read, update, and delete campaigns while keeping progress calculations database-driven.</p></div><?php if(can('campaigns.manage')):?><button class="btn btn-primary" data-modal-open="campaignModal"><i data-lucide="plus"></i>New campaign</button><?php endif;?></section>
<section class="campaign-list reveal stagger-1"><?php if(!$campaigns):?><div class="panel empty-state"><i data-lucide="target"></i><h4>No campaigns yet</h4><p>Create a campaign to start tracking growth.</p></div><?php else:foreach($campaigns as $c):$p=$c['progress'];?><article class="campaign-card"><div class="campaign-card-head"><div><span class="status-chip <?=$c['status']==='active'?'on-track':'neutral'?>"><?=e(ucfirst($c['status']))?></span><h3><?=e($c['name'])?></h3><p><?=e(date('d M Y',strtotime($c['start_date'])))?> → <?=e(date('d M Y',strtotime($c['deadline'])))?> · <?=e($c['timezone'])?></p></div><div class="campaign-big-number"><strong><?=number_format($p['percentage'],1)?>%</strong><span><?=number_format($p['counted'])?> / <?=number_format($p['target'])?></span></div></div><div class="linear-progress"><span style="width:<?=e((string)$p['visual_percentage'])?>%"></span></div><div class="campaign-stats"><div><span>Remaining</span><strong><?=number_format($p['remaining'])?></strong></div><div><span>Daily required</span><strong><?=number_format($p['required_daily'],1)?></strong></div><div><span>Manager</span><strong><?=e($c['manager_name']?:'Unassigned')?></strong></div><div><span>Days remaining</span><strong><?=number_format($p['days_remaining'])?></strong></div></div>
<?php if(can('campaigns.manage')):?><form class="campaign-inline-form" method="post" action="<?=e(url('handlers/campaign-update.php'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$c['id']?>"><label class="span-2">Campaign name<input name="name" value="<?=e($c['name'])?>" required></label><label>Start<input type="date" name="start_date" value="<?=e($c['start_date'])?>" required></label><label>Deadline<input type="date" name="deadline" value="<?=e($c['deadline'])?>" required></label><label>Target<input type="number" name="target_count" min="1" value="<?=$c['target_count']?>" required></label><label>Manager<select name="manager_employee_id"><option value="">Unassigned</option><?php foreach($employees as $emp):?><option value="<?=$emp['id']?>" <?=((int)$c['manager_employee_id']===(int)$emp['id'])?'selected':''?>><?=e($emp['full_name'])?></option><?php endforeach;?></select></label><label>Status<select name="status"><?php foreach(['draft','active','completed','cancelled'] as $s):?><option value="<?=$s?>" <?=$c['status']===$s?'selected':''?>><?=e(ucfirst($s))?></option><?php endforeach;?></select></label><label class="span-2">Notes<textarea name="notes" rows="2"><?=e($c['notes']??'')?></textarea></label><div class="form-actions span-2"><button class="btn btn-soft"><i data-lucide="save"></i>Update campaign</button></div></form><form method="post" action="<?=e(url('handlers/campaign-delete.php'))?>" style="margin-top:10px;display:flex;justify-content:flex-end"><?=csrf_field()?><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn btn-danger" data-confirm="Delete campaign <?=e($c['name'])?>? Campaign registration links will also be removed."><i data-lucide="trash-2"></i>Delete campaign</button></form><?php endif;?></article><?php endforeach;endif;?></section>
<div class="modal" id="campaignModal" aria-hidden="true"><div class="modal-card"><button class="modal-close" data-modal-close><i data-lucide="x"></i></button><p class="eyebrow">Growth configuration</p><h3>Create campaign</h3><form class="form-grid" method="post" action="<?=e(url('handlers/campaign-save.php'))?>"><?=csrf_field()?><label class="span-2">Campaign name<input name="name" required></label><label>Start date<input type="date" name="start_date" required></label><label>Deadline<input type="date" name="deadline" required></label><label>Target drivers<input type="number" name="target_count" min="1" required></label><label>Manager<select name="manager_employee_id"><option value="">Unassigned</option><?php foreach($employees as $emp):?><option value="<?=$emp['id']?>"><?=e($emp['full_name'])?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="active">Active</option><option value="draft">Draft</option></select></label><label class="span-2">Notes<textarea name="notes" rows="3"></textarea></label><div class="form-actions span-2"><button type="button" class="btn btn-soft" data-modal-close>Cancel</button><button class="btn btn-primary">Create campaign</button></div></form></div></div>
<?php include __DIR__.'/includes/footer.php';?>
