<?php
require __DIR__.'/includes/bootstrap.php';
require_permission('drivers.view');
$pdo=db();
$search=trim((string)($_GET['q']??''));$status=trim((string)($_GET['status']??''));$page=max(1,(int)($_GET['page']??1));$per=15;
$where=['1=1'];$params=[];
if($search!==''){$where[]='(d.full_name LIKE ? OR d.phone LIKE ? OR d.driver_code LIKE ?)';$like='%'.$search.'%';array_push($params,$like,$like,$like);}
if($status!==''){$where[]='d.status=?';$params[]=$status;}
$sqlWhere=implode(' AND ',$where);
$q=$pdo->prepare("SELECT COUNT(*) FROM drivers d WHERE $sqlWhere");$q->execute($params);$meta=pagination_meta((int)$q->fetchColumn(),$page,$per);
$q=$pdo->prepare("SELECT d.*,e.full_name employee_name FROM drivers d LEFT JOIN employees e ON e.id=d.assigned_employee_id WHERE $sqlWhere ORDER BY d.registration_at DESC LIMIT {$per} OFFSET {$meta['offset']}");$q->execute($params);$drivers=$q->fetchAll();
$employees=$pdo->query("SELECT id,full_name FROM employees WHERE employment_status='active' ORDER BY full_name")->fetchAll();
$editDriver=null;$editId=(int)($_GET['edit']??0);if($editId&&can('drivers.edit')){$q=$pdo->prepare('SELECT * FROM drivers WHERE id=?');$q->execute([$editId]);$editDriver=$q->fetch()?:null;}
$title='Driver Growth';$active='drivers';include __DIR__.'/includes/header.php';
?>
<section class="section-toolbar reveal"><div><p class="eyebrow">Growth operations</p><h2>Driver registration management</h2><p class="muted">Complete CRUD for driver records, verification, assignment, search, and campaign counting.</p></div><div class="toolbar-actions"><?php if(can('drivers.export')):?><a class="btn btn-soft" href="<?=e(url('handlers/export-drivers.php'))?>"><i data-lucide="download"></i>Export CSV</a><?php endif;?><?php if(can('drivers.create')):?><button class="btn btn-primary" data-modal-open="driverModal"><i data-lucide="user-plus"></i>Add driver</button><?php endif;?></div></section>
<section class="panel reveal stagger-1"><form class="filter-bar" method="get" action="<?=e(url('drivers.php'))?>"><div class="search-field"><i data-lucide="search"></i><input name="q" value="<?=e($search)?>" placeholder="Search name, phone, or driver ID"></div><select name="status"><option value="">All statuses</option><?php foreach(['lead','registered','verification_pending','verified','rejected','inactive'] as $s):?><option value="<?=e($s)?>" <?=$status===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?></option><?php endforeach;?></select><button class="btn btn-soft">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Driver</th><th>Registration</th><th>Status</th><th>Source</th><th>Assigned to</th><th>Actions</th></tr></thead><tbody><?php if(!$drivers):?><tr><td colspan="6"><div class="empty-state compact"><i data-lucide="car-front"></i><h4>No drivers found</h4><p>Add the first driver registration.</p></div></td></tr><?php else:foreach($drivers as $d):?><tr><td><div class="person-cell"><span class="avatar small"><?=e(strtoupper(substr($d['full_name'],0,1)))?></span><div><strong><?=e($d['full_name'])?></strong><small><?=e($d['driver_code'])?> · <?=e($d['phone'])?></small></div></div></td><td><strong><?=e(format_datetime($d['registration_at'],'d M Y'))?></strong><small><?=e(format_datetime($d['registration_at'],'h:i A'))?></small></td><td><span class="status-chip <?=$d['verification_status']==='verified'?'on-track':'neutral'?>"><?=e(ucwords(str_replace('_',' ',$d['status'])))?></span></td><td><?=e($d['registration_source']?:'—')?></td><td><?=e($d['employee_name']?:'Unassigned')?></td><td><div class="toolbar-actions"><?php if($d['verification_status']!=='verified'&&can('drivers.verify')):?><form method="post" action="<?=e(url('handlers/driver-verify.php'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$d['id']?>"><button class="btn btn-xs btn-success" data-confirm="Verify this driver and count the registration if eligible?">Verify</button></form><?php endif;?><?php if(can('drivers.edit')):?><a class="btn btn-xs btn-soft" href="?<?=http_build_query(['q'=>$search,'status'=>$status,'page'=>$meta['page'],'edit'=>$d['id']])?>"><i data-lucide="pencil"></i>Edit</a><form method="post" action="<?=e(url('handlers/driver-delete.php'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$d['id']?>"><button class="btn btn-xs btn-danger" data-confirm="Delete <?=e($d['full_name'])?>? This also removes campaign membership/history for this driver."><i data-lucide="trash-2"></i>Delete</button></form><?php endif;?></div></td></tr><?php endforeach;endif;?></tbody></table></div>
<div class="pagination"><span>Page <?=$meta['page']?> of <?=$meta['pages']?> · <?=number_format($meta['total'])?> records</span><div><?php if($meta['page']>1):?><a class="btn btn-xs btn-soft" href="?<?=http_build_query(['q'=>$search,'status'=>$status,'page'=>$meta['page']-1])?>">Previous</a><?php endif;?><?php if($meta['page']<$meta['pages']):?><a class="btn btn-xs btn-soft" href="?<?=http_build_query(['q'=>$search,'status'=>$status,'page'=>$meta['page']+1])?>">Next</a><?php endif;?></div></div></section>

<div class="modal" id="driverModal" aria-hidden="true"><div class="modal-card"><button class="modal-close" data-modal-close aria-label="Close"><i data-lucide="x"></i></button><p class="eyebrow">New registration</p><h3>Add driver</h3><form class="form-grid" method="post" action="<?=e(url('handlers/driver-save.php'))?>"><?=csrf_field()?><label class="span-2">Full name<input name="full_name" required></label><label>Phone with country code<input name="phone" required placeholder="+974 5xxx xxxx"></label><label>Status<select name="status"><option value="verification_pending">Verification Pending</option><option value="registered">Registered</option><option value="lead">Lead</option><?php if(can('drivers.verify')):?><option value="verified">Verified</option><?php endif;?></select></label><label>Registration source<input name="registration_source" placeholder="Office / Referral / Campaign"></label><label>Assigned employee<select name="assigned_employee_id"><option value="">Unassigned</option><?php foreach($employees as $emp):?><option value="<?=$emp['id']?>"><?=e($emp['full_name'])?></option><?php endforeach;?></select></label><label class="span-2">Notes<textarea name="notes" rows="3"></textarea></label><div class="form-actions span-2"><button type="button" class="btn btn-soft" data-modal-close>Cancel</button><button class="btn btn-primary">Save driver</button></div></form></div></div>

<?php if($editDriver):?><div class="modal open" id="driverEditModal" aria-hidden="false"><div class="modal-card"><a class="modal-close" href="<?=e(url('drivers.php'))?>"><i data-lucide="x"></i></a><p class="eyebrow">Driver CRUD</p><h3>Edit <?=e($editDriver['driver_code'])?></h3><form class="form-grid" method="post" action="<?=e(url('handlers/driver-update.php'))?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=$editDriver['id']?>"><label class="span-2">Full name<input name="full_name" value="<?=e($editDriver['full_name'])?>" required></label><label>Phone<input name="phone" value="<?=e($editDriver['phone'])?>" required></label><label>Status<select name="status"><?php foreach(['lead','registered','verification_pending','verified','rejected','inactive'] as $s):if($s==='verified'&&!can('drivers.verify')&&$editDriver['status']!=='verified')continue;?><option value="<?=$s?>" <?=$editDriver['status']===$s?'selected':''?>><?=e(ucwords(str_replace('_',' ',$s)))?></option><?php endforeach;?></select></label><label>Source<input name="registration_source" value="<?=e($editDriver['registration_source']??'')?>"></label><label>Assigned employee<select name="assigned_employee_id"><option value="">Unassigned</option><?php foreach($employees as $emp):?><option value="<?=$emp['id']?>" <?=((int)$editDriver['assigned_employee_id']===(int)$emp['id'])?'selected':''?>><?=e($emp['full_name'])?></option><?php endforeach;?></select></label><label class="span-2">Notes<textarea name="notes" rows="3"><?=e($editDriver['notes']??'')?></textarea></label><div class="form-actions span-2"><a class="btn btn-soft" href="<?=e(url('drivers.php'))?>">Cancel</a><button class="btn btn-primary">Update driver</button></div></form></div></div><?php endif;?>
<?php include __DIR__.'/includes/footer.php';?>
