<?php
require_once __DIR__.'/includes/bootstrap.php';
if(!installed())redirect('setup.php');
require_once __DIR__.'/includes/public-data.php';
if(!public_bool('public_dashboard_enabled',true)){http_response_code(503);$publicTitle='Dashboard unavailable';include __DIR__.'/includes/public-head.php';?><section class="public-offline"><span><i data-lucide="eye-off"></i></span><h1>Live dashboard is temporarily unavailable.</h1><p>Management has paused the public view.</p><a href="<?=e(url('login.php'))?>">Administrator sign in</a></section><?php include __DIR__.'/includes/public-foot.php';exit;}
$d=public_dashboard_data();extract($d);$publicTitle='Live Operations Dashboard';include __DIR__.'/includes/public-head.php';
$heroBadge=(string)setting('public_hero_badge','Live operations intelligence');$heroTitle=(string)setting('public_hero_title','One screen. Every operational signal.');$heroSubtitle=(string)setting('public_hero_subtitle','Today, yesterday, totals, campaign pace, employee execution, and task progress—updated from Admin in real time.');$notice=trim((string)setting('public_notice',''));
function public_status_label(string $s):string{return ucwords(str_replace('_',' ',$s));}
$dailyLabels=array_map(fn($r)=>date('d M',strtotime($r['d'])),$daily);$customerValues=array_map(fn($r)=>(int)$r['customers'],$daily);$driverValues=array_map(fn($r)=>(int)$r['drivers'],$daily);
?>
<section class="command-hero">
  <div class="hero-copy"><span class="hero-kicker"><i></i><?=e($heroBadge)?></span><h1><?=e($heroTitle)?></h1><p><?=e($heroSubtitle)?></p><?php if($notice!==''):?><div class="hero-notice"><i data-lucide="megaphone"></i><span><?=e($notice)?></span></div><?php endif;?></div>
  <div class="campaign-compact"><div class="campaign-ring" style="--p:<?=min(100,max(0,(float)$progress['visual_percentage']))?>"><span><strong id="publicPercent"><?=number_format($progress['percentage'],1)?>%</strong><small>campaign</small></span></div><div class="campaign-copy"><small><?=e($campaign['name'])?></small><strong><b id="publicCampaignDrivers"><?=number_format($progress['counted'])?></b> / <?=number_format($progress['target'])?> drivers</strong><p><span><?=number_format($progress['remaining'])?> remaining</span><span><?=number_format($progress['days_remaining'])?> days left</span></p></div></div>
</section>
<section class="command-grid">
  <article class="command-panel registration-panel">
    <div class="panel-title"><div><span class="panel-eyebrow">Registration pulse</span><h2>Customers & drivers</h2></div><span class="read-only-chip"><i data-lucide="shield-check"></i>Count only</span></div>
    <div class="count-tiles">
      <div class="count-tile today customer"><span><i data-lucide="user-round-plus"></i></span><div><small>Customers today</small><strong id="publicTodayCustomers"><?=number_format($growth['today_customers'])?></strong><p><?=e(date('d M',strtotime($growth['today_date'])))?></p></div></div>
      <div class="count-tile today driver"><span><i data-lucide="car-front"></i></span><div><small>Drivers today</small><strong id="publicTodayDrivers"><?=number_format($growth['today_drivers'])?></strong><p><?=e(date('d M',strtotime($growth['today_date'])))?></p></div></div>
      <div class="count-tile yesterday customer"><span><i data-lucide="history"></i></span><div><small>Customers yesterday</small><strong id="publicYesterdayCustomers"><?=number_format($growth['yesterday_customers'])?></strong><p><?=e(date('d M',strtotime($growth['yesterday_date'])))?></p></div></div>
      <div class="count-tile yesterday driver"><span><i data-lucide="history"></i></span><div><small>Drivers yesterday</small><strong id="publicYesterdayDrivers"><?=number_format($growth['yesterday_drivers'])?></strong><p><?=e(date('d M',strtotime($growth['yesterday_date'])))?></p></div></div>
      <div class="count-tile total customer"><span><i data-lucide="users-round"></i></span><div><small>Total customers</small><strong id="publicTotalCustomers"><?=number_format($growth['total_customers'])?></strong><p><?=number_format($growth['week_customers'])?> last 7 days</p></div></div>
      <div class="count-tile total driver"><span><i data-lucide="badge-check"></i></span><div><small>Total drivers</small><strong id="publicTotalDrivers"><?=number_format($growth['total_drivers'])?></strong><p><?=number_format($growth['week_drivers'])?> last 7 days</p></div></div>
    </div>
    <div class="trend-card"><div><span>14-day registration trend</span><small>Customer vs driver counts</small></div><div class="trend-chart"><canvas id="publicGrowthChart"></canvas></div></div>
  </article>

  <article class="command-panel performance-panel">
    <div class="panel-title"><div><span class="panel-eyebrow">Employee execution</span><h2>Task completion</h2></div><span class="team-count"><?=number_format($activeEmployees)?> active</span></div>
    <div class="employee-compact-list"><?php if(!$employeePerformance):?><div class="empty-mini">No employee task data yet.</div><?php else:foreach(array_slice($employeePerformance,0,7) as $emp):$pct=(float)$emp['completion_percentage'];?><div class="employee-compact" data-employee-performance="<?=$emp['id']?>"><span class="employee-avatar"><?=e(strtoupper(substr($emp['full_name'],0,1)))?></span><div class="employee-compact-main"><div><strong><?=e($emp['full_name'])?></strong><small><?=e($emp['job_title']?:'Team member')?></small></div><div class="employee-bar"><i style="width:<?=min(100,max(0,$pct))?>%"></i></div><p><span><?=number_format((int)$emp['completed_tasks'])?> / <?=number_format((int)$emp['total_tasks'])?> completed</span><span><?=number_format((int)$emp['overdue_tasks'])?> overdue</span></p></div><strong class="employee-pct" data-employee-pct="<?=$emp['id']?>"><?=number_format($pct,0)?>%</strong></div><?php endforeach;endif;?></div>
    <div class="panel-footer-line"><span><i data-lucide="gauge"></i>Completion is completed ÷ assigned non-cancelled tasks</span><button type="button" data-public-task-open>Open task details <i data-lucide="arrow-up-right"></i></button></div>
  </article>

  <article class="command-panel task-panel">
    <div class="panel-title"><div><span class="panel-eyebrow">Task operations</span><h2>Execution board</h2></div><button class="task-list-button" type="button" data-public-task-open><i data-lucide="list-filter"></i>Task list</button></div>
    <div class="task-summary-grid"><div><span>Open</span><strong id="publicPending"><?=number_format($pending)?></strong><i data-lucide="list-todo"></i></div><div><span>Completed</span><strong id="publicCompleted"><?=number_format($completed)?></strong><i data-lucide="circle-check-big"></i></div><div class="danger"><span>Overdue</span><strong id="publicOverdue"><?=number_format($overdue)?></strong><i data-lucide="triangle-alert"></i></div><div><span>This week</span><strong><?=number_format($completedWeek)?></strong><i data-lucide="sparkles"></i></div></div>
    <div class="recent-task-list"><?php if(!$recentTasks):?><div class="empty-mini">No tasks yet.</div><?php else:foreach(array_slice($recentTasks,0,5) as $task):?><button class="recent-task" type="button" data-public-task-open data-task-id="<?=$task['id']?>"><span class="task-state <?=e($task['status'])?>"></span><div><strong><?=e($task['title'])?></strong><small><?=e($task['assignee']?:'Unassigned')?> · <?=e(public_status_label($task['status']))?></small></div><span class="task-percent"><?=number_format((int)$task['progress'])?>%</span></button><?php endforeach;endif;?></div>
    <div class="campaign-micro"><span><i data-lucide="target"></i><?=number_format($progress['remaining'])?> drivers remaining</span><span><i data-lucide="activity"></i><?=number_format($progress['required_daily'],1)?> required/day</span><span><i data-lucide="calendar-clock"></i><?=e(date('d M',strtotime($progress['deadline'])))?> deadline</span></div>
  </article>
</section>
<section class="command-bottom-strip"><span><i data-lucide="users-round"></i><b><?=number_format($growth['week_customers'])?></b> customers / 7 days</span><span><i data-lucide="car-front"></i><b><?=number_format($growth['week_drivers'])?></b> drivers / 7 days</span><span><i data-lucide="briefcase-business"></i><b><?=number_format($activeEmployees)?></b> active employees</span><span><i data-lucide="clock-3"></i>Updated automatically · <?=e((string)setting('business_timezone','Asia/Qatar'))?></span></section>

<div class="public-task-modal" id="publicTaskModal" aria-hidden="true"><div class="public-task-backdrop" data-public-task-close></div><section class="public-task-drawer" role="dialog" aria-modal="true" aria-labelledby="publicTaskTitle"><header><div><span class="panel-eyebrow">Read-only operations</span><h2 id="publicTaskTitle">Task list & details</h2><p>Select a task to see the full description, assignee, status, priority, due date, and progress.</p></div><button type="button" data-public-task-close aria-label="Close task list"><i data-lucide="x"></i></button></header><div class="task-drawer-layout"><aside class="task-drawer-list"><div class="task-filter-row"><button class="active" type="button" data-task-filter="all">All</button><?php foreach(array_slice($employeePerformance,0,7) as $emp):?><button type="button" data-task-filter="employee-<?=$emp['id']?>"><?=e(explode(' ',$emp['full_name'])[0])?></button><?php endforeach;?></div><div class="drawer-scroll"><?php foreach($recentTasks as $i=>$task):?><button class="drawer-task-item <?=$i===0?'active':''?>" type="button" data-public-task-item data-task-employee="employee-<?=e((string)($task['primary_assignee_id']??''))?>" data-task-json='<?=e(json_encode(['id'=>(int)$task['id'],'code'=>$task['task_code'],'title'=>$task['title'],'description'=>$task['description']?:'No description provided.','assignee'=>$task['assignee']?:'Unassigned','category'=>$task['category']?:'General','status'=>public_status_label($task['status']),'status_key'=>$task['status'],'priority'=>ucfirst($task['priority']),'progress'=>(int)$task['progress'],'due'=>$task['due_at']?format_datetime($task['due_at'],'d M Y, h:i A'):'No due date'],JSON_UNESCAPED_SLASHES))?>'><span class="task-state <?=e($task['status'])?>"></span><div><strong><?=e($task['title'])?></strong><small><?=e($task['assignee']?:'Unassigned')?> · <?=number_format((int)$task['progress'])?>%</small></div><i data-lucide="chevron-right"></i></button><?php endforeach;?></div></aside><article class="task-detail-pane" id="publicTaskDetail"><div class="task-detail-empty"><i data-lucide="list-checks"></i><p>Select a task to view its details.</p></div></article></div></section></div>
<script>window.__IDRIVER_PUBLIC_DATA__=<?=json_encode(['growth'=>['labels'=>$dailyLabels,'customers'=>$customerValues,'drivers'=>$driverValues]],JSON_UNESCAPED_SLASHES)?>;</script>
<?php include __DIR__.'/includes/public-foot.php';?>
