<?php
require __DIR__.'/includes/bootstrap.php';require_permission('settings.manage');$rows=db()->query('SELECT * FROM system_settings ORDER BY setting_key')->fetchAll();$settings=[];foreach($rows as $r)$settings[$r['setting_key']]=$r['setting_value'];
function checked_setting(array $settings,string $key,bool $default=true):string{$v=$settings[$key]??($default?'1':'0');return in_array(strtolower((string)$v),['1','true','yes','on'],true)?'checked':'';}
$title='System Settings';$active='settings';include __DIR__.'/includes/header.php';$brandLogo=brand_logo_url();?>
<section class="section-toolbar reveal"><div><p class="eyebrow">Administration</p><h2>System settings</h2><p class="muted">Control business settings, branding, public dashboard content, and what visitors are allowed to see.</p></div><div class="toolbar-actions"><a class="btn btn-soft" target="_blank" href="<?=e(url())?>"><i data-lucide="external-link"></i>View public dashboard</a></div></section>
<section class="settings-layout reveal stagger-1"><form class="panel settings-form" method="post" action="<?=e(url('handlers/settings-save.php'))?>"><?=csrf_field()?><div class="panel-heading"><div><p class="eyebrow">General</p><h3>Business configuration</h3></div></div><label>Company name<input name="company_name" value="<?=e($settings['company_name']??'iDriver Technology')?>"></label><label>Business timezone<select name="business_timezone"><option value="Asia/Qatar" <?=($settings['business_timezone']??'Asia/Qatar')==='Asia/Qatar'?'selected':''?>>Asia/Qatar</option><option value="UTC" <?=($settings['business_timezone']??'')==='UTC'?'selected':''?>>UTC</option></select></label><label>Admin dashboard refresh seconds<input type="number" min="10" max="300" name="dashboard_refresh_seconds" value="<?=e($settings['dashboard_refresh_seconds']??'20')?>"><small>Minimum 10 seconds to avoid excessive polling.</small></label><label>Date format<input name="date_format" value="<?=e($settings['date_format']??'d M Y')?>"></label><button class="btn btn-primary">Save general settings</button></form>
<aside class="panel settings-info"><span class="metric-icon blue"><i data-lucide="shield-check"></i></span><h3>Public is visual, Admin stays in control</h3><p>The public dashboard can show operational progress and employee task performance, but every create, edit, verification, assignment, settings, and export action remains protected.</p><div class="security-list"><span><i data-lucide="check"></i>No public edit controls</span><span><i data-lucide="check"></i>No driver phone numbers</span><span><i data-lucide="check"></i>No employee email/contact details</span><span><i data-lucide="check"></i>Admin-controlled branding and visibility</span></div></aside></section>

<form class="panel public-settings-panel reveal stagger-2" method="post" enctype="multipart/form-data" action="<?=e(url('handlers/settings-save.php'))?>"><?=csrf_field()?><div class="panel-heading"><div><p class="eyebrow">Brand & Public Experience</p><h3>Public Dashboard Control Center</h3><p class="muted">Update logo, navigation identity, public content, live refresh, and visibility without editing PHP.</p></div><a class="text-link" target="_blank" href="<?=e(url())?>">Preview public view</a></div>
<div class="branding-settings"><div class="brand-preview-card"><div class="brand-preview-logo"><?php if($brandLogo):?><img src="<?=e($brandLogo)?>" alt="Current navbar logo"><?php else:?><span>iD</span><?php endif;?></div><div><strong><?=e($settings['company_name']??'iDriver Technology')?></strong><small><?=e($settings['public_nav_subtitle']??'Operations & Growth Command Center')?></small></div></div><div class="brand-upload-fields"><label>Navbar logo<input type="file" name="brand_logo" accept="image/png,image/jpeg,image/webp"><small>PNG, JPG or WebP. Maximum 2 MB. Recommended transparent logo, at least 256 × 256.</small></label><?php if($brandLogo):?><label class="inline-check"><input type="checkbox" name="remove_brand_logo" value="1"><span>Remove current logo and use the iD fallback mark</span></label><?php endif;?><label>Navbar subtitle<input name="public_nav_subtitle" maxlength="100" value="<?=e($settings['public_nav_subtitle']??'Operations & Growth Command Center')?>"></label></div></div>
<div class="public-settings-grid"><div class="public-settings-copy"><label>Public badge<input name="public_hero_badge" maxlength="80" value="<?=e($settings['public_hero_badge']??'Live operations intelligence')?>"></label><label>Hero title<input name="public_hero_title" maxlength="150" value="<?=e($settings['public_hero_title']??'Growth in motion. Progress you can see.')?>"></label><label>Hero subtitle<textarea name="public_hero_subtitle" rows="3" maxlength="400"><?=e($settings['public_hero_subtitle']??'A live, read-only view of iDriver growth, campaign momentum, team execution, and employee task completion.')?></textarea></label><label>Public announcement<textarea name="public_notice" rows="2" maxlength="300" placeholder="Optional message displayed below the hero"><?=e($settings['public_notice']??'')?></textarea></label><div class="form-grid"><label>Public refresh seconds<input type="number" min="10" max="300" name="public_refresh_seconds" value="<?=e($settings['public_refresh_seconds']??'20')?>"></label><label>Footer text<input name="public_footer_text" maxlength="180" value="<?=e($settings['public_footer_text']??'Live operations visibility powered by the iDriver Command Center.')?>"></label></div></div>
<div class="public-visibility"><div class="visibility-head"><span class="metric-icon indigo"><i data-lucide="eye"></i></span><div><strong>Visibility controls</strong><small>Choose exactly what appears publicly.</small></div></div>
<label class="toggle-row"><span><strong>Public dashboard</strong><small>Master switch for the complete public view</small></span><input type="checkbox" name="public_dashboard_enabled" value="1" <?=checked_setting($settings,'public_dashboard_enabled')?>><i></i></label>
<label class="toggle-row"><span><strong>Driver Growth</strong><small>Campaign progress, pace, and registration chart</small></span><input type="checkbox" name="public_show_driver_growth" value="1" <?=checked_setting($settings,'public_show_driver_growth')?>><i></i></label>
<label class="toggle-row"><span><strong>Employee Performance</strong><small>Employee-by-employee 0–100% task completion visuals</small></span><input type="checkbox" name="public_show_employee_performance" value="1" <?=checked_setting($settings,'public_show_employee_performance')?>><i></i></label>
<label class="toggle-row"><span><strong>Employee Task Lists</strong><small>Task titles, status, priority, due date, and progress under each employee</small></span><input type="checkbox" name="public_show_employee_tasks" value="1" <?=checked_setting($settings,'public_show_employee_tasks')?>><i></i></label>
<label class="toggle-row"><span><strong>Operations</strong><small>Task counts and operational execution summary</small></span><input type="checkbox" name="public_show_operations" value="1" <?=checked_setting($settings,'public_show_operations')?>><i></i></label>
<label class="toggle-row"><span><strong>Recent task table</strong><small>Read-only team task activity table</small></span><input type="checkbox" name="public_show_task_feed" value="1" <?=checked_setting($settings,'public_show_task_feed')?>><i></i></label>
<label class="toggle-row"><span><strong>Team</strong><small>Aggregate active headcount and departments</small></span><input type="checkbox" name="public_show_team" value="1" <?=checked_setting($settings,'public_show_team')?>><i></i></label>
<label class="toggle-row"><span><strong>Campaigns</strong><small>Campaign names, dates, status, and target</small></span><input type="checkbox" name="public_show_campaigns" value="1" <?=checked_setting($settings,'public_show_campaigns')?>><i></i></label>
<label class="toggle-row"><span><strong>Activity</strong><small>Privacy-safe registration activity stream</small></span><input type="checkbox" name="public_show_activity" value="1" <?=checked_setting($settings,'public_show_activity')?>><i></i></label></div></div><div class="public-settings-actions"><span><i data-lucide="info"></i>Logo, branding and visibility changes appear on the public dashboard immediately after save.</span><button class="btn btn-primary"><i data-lucide="save"></i>Save public dashboard</button></div></form>

<section class="panel reveal stagger-2" style="margin-top:22px"><div class="panel-heading"><div><p class="eyebrow">Demo workspace</p><h3>Sample data for CRUD testing</h3><p class="muted">Populate the current database with realistic records without using phpMyAdmin or the command line.</p></div><span class="status-chip on-track">Safe seed</span></div><div class="campaign-stats"><div><span>Sample employees</span><strong>6</strong></div><div><span>Sample driver registrations</span><strong>45</strong></div><div><span>Employee tasks</span><strong>30</strong></div><div><span>Completion profiles</span><strong>100 → 0%</strong></div></div><p class="muted" style="margin-top:14px">Demo users all use password <strong>Demo@12345</strong>. Sample emails include <strong>layla.demo@idriver.local</strong> and <strong>omar.demo@idriver.local</strong>.</p><form method="post" action="<?=e(url('handlers/demo-seed.php'))?>" style="margin-top:16px"><?=csrf_field()?><button class="btn btn-primary" data-confirm="Load the sample employees, 45 driver registrations, and 30 tasks into this database?"><i data-lucide="database-zap"></i><?=((string)setting('demo_data_loaded','0')==='1')?'Demo data already loaded':'Load demo data'?></button></form></section>
<?php include __DIR__.'/includes/footer.php';?>
