<?php
require __DIR__.'/includes/bootstrap.php';
if(installed()) redirect('login.php');
$title='First-time setup';
$requirements=[
 ['label'=>'PHP 8.2 or newer','ok'=>version_compare(PHP_VERSION,'8.2.0','>=')],
 ['label'=>'PDO extension','ok'=>extension_loaded('pdo')],
 ['label'=>'PDO MySQL extension','ok'=>extension_loaded('pdo_mysql')],
 ['label'=>'OpenSSL extension','ok'=>extension_loaded('openssl')],
];
$allRequirements=!in_array(false,array_column($requirements,'ok'),true);
$dbCfg=$_SESSION['_setup_db']??['host'=>config('db.host'),'port'=>config('db.port'),'database'=>config('db.database'),'username'=>config('db.username'),'password'=>config('db.password')];unset($_SESSION['_setup_db']);
$schemaReady=schema_ready();
include __DIR__.'/includes/guest-head.php';
?>
<main class="setup-shell"><section class="setup-visual"><div class="setup-grid"></div><div class="setup-orb setup-orb-one"></div><div class="setup-orb setup-orb-two"></div><div class="setup-brand"><div class="brand-symbol lg">iD</div><div><strong>iDriver</strong><span>Operations & Growth Command Center</span></div></div><div class="setup-copy"><span class="setup-kicker"><span class="pulse-dot"></span>Plain PHP local installation</span><h1>Open the project.<br><em>Setup happens here.</em></h1><p>No Laravel, no Artisan, no Composer command, no SQL command line, and no <code>/public</code> URL.</p><div class="setup-steps"><div class="done"><b><i data-lucide="check"></i></b><span><strong>Plain PHP detected</strong><small>Direct .php page architecture</small></span></div><div class="<?=$schemaReady?'done':'active'?>"><b><i data-lucide="<?=$schemaReady?'check':'database'?>"></i></b><span><strong>Database preparation</strong><small>MySQL tables and seed data</small></span></div><div class="active"><b><i data-lucide="user-round-check"></i></b><span><strong>Create administrator</strong><small>Secure Super Administrator account</small></span></div><div><b><i data-lucide="layout-dashboard"></i></b><span><strong>Launch public dashboard</strong><small>The project root becomes the live public view</small></span></div></div></div><div class="setup-live"><span class="pulse-dot"></span><span>XAMPP-ready PHP application</span></div></section>
<section class="setup-panel"><div class="setup-card"><div class="setup-card-head"><div class="login-icon"><i data-lucide="sparkles"></i></div><div><p class="eyebrow">One-time configuration</p><h2>Finish setup</h2><p>Standard XAMPP defaults are already filled in.</p></div></div>
<?php if($success=flash('success')):?><div class="form-alert success"><?=e($success)?></div><?php endif;?><?php if($error=flash('error')):?><div class="form-alert error"><i data-lucide="triangle-alert"></i><span><?=e($error)?></span></div><?php endif;?>
<div class="setup-checks"><?php foreach($requirements as $item):?><div class="<?=$item['ok']?'ok':'bad'?>"><i data-lucide="<?=$item['ok']?'circle-check':'circle-x'?>"></i><span><?=e($item['label'])?></span></div><?php endforeach;?></div>
<?php if(!$allRequirements):?><div class="setup-blocked"><strong>Enable the failed PHP extension in XAMPP.</strong><p>Restart Apache and refresh this page. No command line is required.</p></div><?php else:?><form method="post" action="<?=e(url('handlers/setup-process.php'))?>" class="form-stack setup-form"><?=csrf_field()?>
<div class="setup-section-title"><span>Administrator</span><small>Your management login</small></div><div class="setup-two-col"><label>Full name<input type="text" name="name" value="<?=e(old('name'))?>" required placeholder="System Administrator"></label><label>Email address<input type="email" name="email" value="<?=e(old('email'))?>" required placeholder="admin@idriver.qa"></label></div><div class="setup-two-col"><label>Password<div class="password-wrap"><input type="password" name="password" minlength="12" required placeholder="Minimum 12 characters"><button type="button" class="password-toggle" data-password-toggle><i data-lucide="eye"></i></button></div></label><label>Confirm password<div class="password-wrap"><input type="password" name="password_confirmation" minlength="12" required placeholder="Repeat password"><button type="button" class="password-toggle" data-password-toggle><i data-lucide="eye"></i></button></div></label></div>
<details class="db-advanced"><summary><span><i data-lucide="database"></i>Database settings</span><small>Usually you do not need to change these</small></summary><div class="db-fields"><div class="setup-two-col"><label>Host<input name="db_host" value="<?=e($dbCfg['host'])?>" required></label><label>Port<input name="db_port" value="<?=e($dbCfg['port'])?>" required></label></div><div class="setup-two-col"><label>Database<input name="db_database" value="<?=e($dbCfg['database'])?>" required></label><label>MySQL username<input name="db_username" value="<?=e($dbCfg['username'])?>" required></label></div><label>MySQL password<input type="password" name="db_password" value="<?=e($dbCfg['password'])?>" placeholder="Blank for standard XAMPP root"></label></div></details>
<button class="btn btn-primary btn-lg full setup-submit" type="submit"><span>Complete setup & continue</span><i data-lucide="arrow-right"></i></button><p class="login-note"><i data-lucide="shield-check"></i>After setup, the project root opens the public dashboard. Use Admin Sign In for management.</p></form><?php endif;?></div></section></main>
<?php include __DIR__.'/includes/guest-foot.php';?>
