<?php
require_auth();
$user=current_user();
$title=$title??'Overview';
$active=$active??'';
$unread=0; try{$q=db()->prepare('SELECT COUNT(*) FROM notifications WHERE user_id=? AND read_at IS NULL');$q->execute([current_user_id()]);$unread=(int)$q->fetchColumn();}catch(Throwable){}
$refresh=(int)setting('dashboard_refresh_seconds',config('app.dashboard_refresh_seconds',20));
$brandLogo=brand_logo_url();$companyName=(string)setting('company_name','iDriver Technology');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?=e(csrf_token())?>"><title><?=e($title)?> · iDriver Command Center</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?=e(url('assets/css/style.css'))?>"><link rel="stylesheet" href="<?=e(url('assets/css/neo-admin.css'))?>"><script defer src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script defer src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script></head>
<body><div class="refresh-curtain" aria-hidden="true"><div class="refresh-mark"><span>iD</span></div><div class="refresh-line"></div></div>
<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><?php if($brandLogo):?><div class="brand-symbol brand-image"><img src="<?=e($brandLogo)?>" alt="<?=e($companyName)?> logo"></div><?php else:?><div class="brand-symbol">iD</div><?php endif;?><div><strong><?=e($companyName)?></strong><small>Command Center</small></div></div>
<nav class="nav-list" aria-label="Primary navigation">
<a class="nav-item <?=$active==='dashboard'?'is-active':''?>" href="<?=e(url('dashboard.php'))?>"><i data-lucide="layout-dashboard"></i><span>Overview</span></a>
<?php if(can('drivers.view')):?><a class="nav-item <?=$active==='drivers'?'is-active':''?>" href="<?=e(url('drivers.php'))?>"><i data-lucide="car-front"></i><span>Driver Growth</span></a><?php endif;?>
<?php if(can('employees.view')):?><a class="nav-item <?=$active==='employees'?'is-active':''?>" href="<?=e(url('employees.php'))?>"><i data-lucide="users"></i><span>Employees</span></a><?php endif;?>
<?php if(can('tasks.view')):?><a class="nav-item <?=$active==='tasks'?'is-active':''?>" href="<?=e(url('tasks.php'))?>"><i data-lucide="square-check-big"></i><span>Tasks</span></a><?php endif;?>
<a class="nav-item <?=$active==='activity'?'is-active':''?>" href="<?=e(url('daily-activity.php'))?>"><i data-lucide="calendar-days"></i><span>Daily Activity</span></a>
<?php if(can('campaigns.view')):?><a class="nav-item <?=$active==='campaigns'?'is-active':''?>" href="<?=e(url('campaigns.php'))?>"><i data-lucide="target"></i><span>Campaigns</span></a><?php endif;?>
<?php if(can('reports.view')):?><a class="nav-item <?=$active==='reports'?'is-active':''?>" href="<?=e(url('reports.php'))?>"><i data-lucide="chart-no-axes-combined"></i><span>Reports</span></a><?php endif;?>
<a class="nav-item <?=$active==='notifications'?'is-active':''?>" href="<?=e(url('notifications.php'))?>"><i data-lucide="bell"></i><span>Notifications</span><?php if($unread):?><b class="nav-badge"><?=$unread?></b><?php endif;?></a>
<?php if(can('audit.view')):?><a class="nav-item <?=$active==='audit'?'is-active':''?>" href="<?=e(url('audit-logs.php'))?>"><i data-lucide="scroll-text"></i><span>Audit Logs</span></a><?php endif;?>
<?php if(can('settings.manage')):?><a class="nav-item <?=$active==='settings'?'is-active':''?>" href="<?=e(url('settings.php'))?>"><i data-lucide="settings"></i><span>Settings</span></a><?php endif;?>
</nav><div class="sidebar-footer"><div class="mini-status"><span class="pulse-dot"></span><div><strong>Live sync</strong><small>Auto-refresh active</small></div></div></div></aside>
<div class="mobile-backdrop" id="mobileBackdrop"></div><section class="workspace"><header class="topbar"><div class="topbar-left"><button class="icon-btn mobile-menu" id="menuBtn" aria-label="Open menu"><i data-lucide="menu"></i></button><div><p class="eyebrow">Operations workspace</p><h1><?=e($title)?></h1></div></div><div class="topbar-actions"><a class="top-public-link" target="_blank" href="<?=e(url())?>"><i data-lucide="globe-2"></i>Public dashboard</a><div class="timezone-chip"><i data-lucide="clock-3"></i><span><?=e(date('D, d M Y'))?> · <?=e((string)setting('business_timezone',config('app.timezone','Asia/Qatar')))?></span></div><?php if(can('tasks.create')):?><a class="btn btn-primary hide-sm" href="<?=e(url('tasks.php#new-task'))?>"><i data-lucide="plus"></i>New task</a><?php endif;?><a class="icon-btn" href="<?=e(url('notifications.php'))?>" aria-label="Notifications"><i data-lucide="bell"></i><?php if($unread):?><span class="notification-dot"></span><?php endif;?></a><details class="profile-menu"><summary><span class="avatar"><?=e(strtoupper(substr($user['full_name']??$user['email']??'U',0,1)))?></span><span class="profile-copy"><strong><?=e($user['full_name']??'User')?></strong><small><?=e($user['role_name']??'Account')?></small></span><i data-lucide="chevron-down"></i></summary><div class="profile-dropdown"><p><?=e($user['email']??'')?></p><form method="post" action="<?=e(url('handlers/logout.php'))?>"><?=csrf_field()?><button class="dropdown-action" type="submit"><i data-lucide="log-out"></i>Sign out</button></form></div></details></div></header>
<main class="content-area page-enter"><?php if($success=flash('success')):?><div class="toast toast-success" data-toast><i data-lucide="circle-check"></i><span><?=e($success)?></span></div><?php endif;?><?php if($error=flash('error')):?><div class="toast toast-error" data-toast><i data-lucide="triangle-alert"></i><span><?=e($error)?></span></div><?php endif;?>
