<?php
$publicTitle=$publicTitle??'Live Operations Dashboard';
$company=(string)setting('company_name','iDriver Technology');
$navSubtitle=(string)setting('public_nav_subtitle','Operations & Growth Command Center');
$logo=brand_logo_url();
$refresh=max(10,min(300,(int)setting('public_refresh_seconds',setting('dashboard_refresh_seconds','20'))));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#e9eef5"><title><?=e($publicTitle)?> · <?=e($company)?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?=e(url('assets/css/public.css'))?>"><script defer src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script defer src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script></head><body data-public-dashboard data-refresh="<?=$refresh?>"><div class="public-loader" aria-hidden="true"><div class="loader-shell"><div class="loader-logo"><?php if($logo):?><img src="<?=e($logo)?>" alt=""><?php else:?><span>iD</span><?php endif;?></div><div class="loader-copy"><strong><?=e($company)?></strong><small>Loading live operations</small></div></div><div class="loader-track"><i></i></div></div>
<header class="public-nav"><a class="public-brand" href="<?=e(url())?>"><?php if($logo):?><span class="brand-logo"><img src="<?=e($logo)?>" alt="<?=e($company)?> logo"></span><?php else:?><span class="brand-mark">iD</span><?php endif;?><span class="brand-copy"><strong><?=e($company)?></strong><small><?=e($navSubtitle)?></small></span></a><nav><a href="#overview">Overview</a><a href="#growth">Growth</a><a href="#performance">Team Performance</a><a href="#operations">Tasks</a><a href="#campaigns">Campaigns</a></nav><div class="nav-actions"><span class="live-badge"><i></i>Live data</span><a class="admin-link" href="<?=e(url('login.php'))?>"><i data-lucide="shield-check"></i><span>Admin</span></a></div></header>
<main class="public-main">
